# -*- coding: utf-8 -*-
"""vectors_example.ipynb

Automatically generated by Colab.

"""

import logging
import warnings
import os

os.environ["TRANSFORMERS_VERBOSITY"] = "error"
logging.getLogger("sentence_transformers").setLevel(logging.ERROR)
logging.getLogger("transformers").setLevel(logging.ERROR)
warnings.filterwarnings("ignore")

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer('all-MiniLM-L6-v2')

words = ["banana", "banana tree", "paypal"]
embeddings = model.encode(words)

print(embeddings[0][:5])
print(len(embeddings[0]))

banana_vs_strawberry = cosine_similarity([embeddings[0]], [embeddings[1]])
banana_vs_destruction = cosine_similarity([embeddings[0]], [embeddings[2]])

print("banana vs strawberry:", banana_vs_strawberry)
print("banana vs destruction:", banana_vs_destruction)

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q --upgrade pageindex

from pageindex import PageIndexClient
import pageindex.utils as utils
from huggingface_hub import AsyncInferenceClient
import os, requests
import json
from huggingface_hub import AsyncInferenceClient

PAGEINDEX_API_KEY = "YOUR_PAGEINDEX_API_KEY"
HF_TOKEN = "YOUR_HF_KEY"
pi_client = PageIndexClient(api_key=PAGEINDEX_API_KEY)

async def call_llm(prompt, model="meta-llama/Llama-3.1-8B-Instruct", temperature=0):
    client = AsyncInferenceClient(token=HF_TOKEN)
    response = await client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        temperature=temperature
    )
    return response.choices[0].message.content.strip()

pdf_url = "https://cdn2.hubspot.net/hubfs/2854653/Digital%20Files/digital-knowledge-center/ebook/microservices-eBook.pdf"
pdf_path = os.path.join("../data", pdf_url.split('/')[-1])
os.makedirs(os.path.dirname(pdf_path), exist_ok=True)

response = requests.get(pdf_url)
with open(pdf_path, "wb") as f:
    f.write(response.content)
print(f"Downloaded {pdf_url}")

doc_id = pi_client.submit_document(pdf_path)["doc_id"]
print('Document Submitted:', doc_id)

if pi_client.is_retrieval_ready(doc_id):
    tree = pi_client.get_tree(doc_id, node_summary=True)['result']
    print('Simplified Tree Structure of the Document:')
    utils.print_tree(tree)
else:
    print("Processing document, please try again later...")

import json

query = "What is the difference between monolith and microservices"

tree_without_text = utils.remove_fields(tree.copy(), fields=['text'])

search_prompt = f"""
You are given a question and a tree structure of a document.
Each node contains a node id, node title, and a corresponding summary.
Your task is to find all nodes that are likely to contain the answer to the question.

Question: {query}

Document tree structure:
{json.dumps(tree_without_text, indent=2)}

Please reply in the following JSON format:
{{
    "thinking": "<Your thinking process on which nodes are relevant to the question>",
    "node_list": ["node_id_1", "node_id_2", ..., "node_id_n"]
}}
Directly return the final JSON structure. Do not output anything else.
"""

tree_search_result = await call_llm(search_prompt)

node_map = utils.create_node_mapping(tree)
tree_search_result_json = json.loads(tree_search_result)

print('Reasoning Process:')
utils.print_wrapped(tree_search_result_json['thinking'])

print('\nRetrieved Nodes:')
for node_id in tree_search_result_json["node_list"]:
    node = node_map[node_id]
    print(f"Node ID: {node['node_id']}\t Page: {node['page_index']}\t Title: {node['title']}")

node_list = json.loads(tree_search_result)["node_list"]
relevant_content = "\n\n".join(node_map[node_id]["text"] for node_id in node_list)

print('Retrieved Context:\n')
utils.print_wrapped(relevant_content[:1000] + '...')

answer_prompt = f"""
Answer the question based on the context:

Question: {query}
Context: {relevant_content}

Provide a clear, concise answer based only on the context provided.
"""

print('Generated Answer:\n')
answer = await call_llm(answer_prompt)
utils.print_wrapped(answer)

